RETRIEVER = "retriever"
GENERATE = "generate"
WEB_SEARCH = "web_search"
ANSWER = "answer"
ROUTER = "router"
FAILURE = "failure"
REWRITE_QUERY = "rewrite_query"
GLOBAL_SUMMARIZER = "global_summarizer"
DOCUMENT_SUMMARIZER = "document_summarizer"
MAX_WEB_SEARCH = 2

SUMMARIZER_LLM="gemini-2.5-flash"
QUERY_LLM="gemini-2.5-pro"
REWRITE_QUERY_LLM="gemini-2.0-flash"
NODE_GENERATION_LLM="gemini-2.5-flash"
NODE_DESCRIPTION_LLM="gemini-2.0-flash"
STOP_WORDS_EXTRACTION_LLM="gemini-2.5-flash"
IMAGE_PARSER_LLM = "gemma3:12b"